=pod

=head1 NAME

File::Find::Fast

=head1 SYNOPSIS

A module to find files much more quickly than `File::Find`.
The trick is that it doesn't `stat` any files.

=head2 Quick start

    use strict;
    use warnings;
    use Data::Dumper qw/Dumper/;
    use File::Find::Fast qw/find/;

    my $files = find("some/directory");
    print Dumper $files

=head1 DESCRIPTION

I purely made this module because I wanted a fast way to list files without running stat.
By using this module, you do not get file information directly.
You would have to use `stat` or similar methods as a follow up.

=head1 METHODS

=over

=item find($dir)

Finds all files in a directory, recursively.

    my $files = find("t/files");
    print join("\n", @$files);
    print "\n";

=back


=cut

=pod

=over

=item find_iterator

An iterator for finding files. Breadth first.
This is useful if you don't want to load all the files into memory first.

    $it = find_iterator("t/files");
    while(my $f=$it->()){
      next if($f =~ /2/); # skip any file that has a 2 in it
      print $f."\n";
    }

=back


=cut

